# Generated by Django 2.2.2 on 2019-06-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunr_app', '0002_auto_20190610_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tunr_app.Episode'),
        ),
    ]
