# Generated by Django 2.2.2 on 2019-06-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr_app', '0004_auto_20190611_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='episode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
