# Generated by Django 2.2.2 on 2019-06-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr_app', '0005_comment_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='episode',
        ),
        migrations.AddField(
            model_name='review',
            name='episode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
